# Generated by Django 4.1 on 2022-08-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_item_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='carts_item_title_6ae2c0_idx',
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['title', 'description', 'price', 'quant_in', 'slug'], name='carts_item_title_1fde4b_idx'),
        ),
    ]
