# Generated by Django 4.1 on 2022-08-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_item_carts_item_title_6ae2c0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
