# Generated by Django 4.1 on 2022-08-25 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cart_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='active',
        ),
    ]
